#! /usr/bin/env bash

source /opt/ros/humble/setup.bash

ros2 launch foxglove_bridge foxglove_bridge_launch.xml &
ros2 launch rosbridge_server rosbridge_websocket_launch.xml port:=7492 &
while true; do sleep 1000; done